version: '3.8'


services:
  liquors-quiz-app:
    image: dleclercpro/liquors-quiz:latest
    container_name: liquors-quiz-app
    ports:
      - 80:8000
    depends_on:
      - liquors-quiz-redis
    environment:
      NODE_ENV: production

  liquors-quiz-redis:
    image: redis:latest
    container_name: liquors-quiz-redis
    volumes:
      - data:/data


volumes:
  data: