version: '3.8'


services:
  liquors-quiz-app:
    image: dleclercpro/liquors-quiz:v2.4.0
    container_name: liquors-quiz-app
    networks:
      - custom
    depends_on:
      - liquors-quiz-redis
    environment:
      NODE_ENV: production

  liquors-quiz-nginx:
    container_name: liquors-quiz-nginx
    image: dleclercpro/ssl-reverse-proxy:latest
    restart: always
    ports:      # Comment out when getting SSL certs for the first time
      - 443:443 # HTTPS
      - 80:80   # HTTP
    networks:
      - custom
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
    depends_on:
      - liquors-quiz-app
    env_file:
      - .env

  liquors-quiz-redis:
    image: redis:latest
    container_name: liquors-quiz-redis
    restart: always
    networks:
      - custom
    volumes:
      - redis:/data


volumes:
  redis:
  letsencrypt:


networks:
  # Custom network to communicate with external services/containers
  custom:
    external: true