version: '3.8'


services:
  quiz-app:
    image: dleclercpro/quiz:v3.7.0
    container_name: quiz-app
    networks:
      - custom
    depends_on:
      - quiz-redis
    environment:
      NODE_ENV: production

  quiz-nginx:
    container_name: quiz-nginx
    image: dleclercpro/reverse-proxy:latest
    restart: always
    ports:      # Comment out when getting SSL certs for the first time
      - 443:443 # HTTPS
      - 80:80   # HTTP
    networks:
      - custom
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
      - dhparams:/usr/dhparams       # Keep DH params file
    depends_on:
      - quiz-app
    env_file:
      - .env

  quiz-redis:
    image: redis:latest
    container_name: quiz-redis
    restart: always
    networks:
      - custom
    volumes:
      - redis:/data


volumes:
  redis:
  letsencrypt:
  dhparams:


networks:
  # Custom network to communicate with external services/containers
  custom:
    external: true