version: '3.8'


services:
  liquors-app:
    image: dleclercpro/liquors-quiz:latest
    container_name: liquors-app
    ports:
      - 8000:8000
    depends_on:
      - liquors-redis
    environment:
      NODE_ENV: production

  liquors-redis:
    image: redis:latest
    container_name: liquors-redis
    volumes:
      - data:/data


volumes:
  data: