version: '3.8'


services:
  quiz-app:
    image: dleclercpro/quiz:3.12.1
    container_name: quiz-app
    ports:
      - 80:8000
    depends_on:
      - quiz-redis
    environment:
      NODE_ENV: production

  quiz-redis:
    image: redis:latest
    container_name: quiz-redis
    volumes:
      - redis:/data


volumes:
  redis: